<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>archivepack</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="WolvenKit.RED4"><HintPath>C:\Users\sebaj\Documents\CP77_mods\WolvenKit-8.20.0\WolvenKit.RED4.dll</HintPath></Reference>
    <Reference Include="WolvenKit.Core"><HintPath>C:\Users\sebaj\Documents\CP77_mods\WolvenKit-8.20.0\WolvenKit.Core.dll</HintPath></Reference>
    <Reference Include="WolvenKit.Common"><HintPath>C:\Users\sebaj\Documents\CP77_mods\WolvenKit-8.20.0\WolvenKit.Common.dll</HintPath></Reference>
    <Reference Include="System.Collections.Immutable"><HintPath>C:\Users\sebaj\Documents\CP77_mods\WolvenKit-8.20.0\System.Collections.Immutable.dll</HintPath></Reference>
    <Reference Include="System.Text.Json"><HintPath>C:\Users\sebaj\Documents\CP77_mods\WolvenKit-8.20.0\System.Text.Json.dll</HintPath></Reference>
    <Reference Include="System.Text.Encodings.Web"><HintPath>C:\Users\sebaj\Documents\CP77_mods\WolvenKit-8.20.0\System.Text.Encodings.Web.dll</HintPath></Reference>
  </ItemGroup>
</Project>
